INSERT INTO `ai_term_categories` (`id`, `locale`, `translation_key`, `name`, `slug`, `description`, `icon`, `sort_order`, `created_at`, `updated_at`) VALUES
  ('ai-term-category:zh:ai-basics', 'zh', 'ai-basics', 'AI 基础概念', 'ai-basics', 'AI/机器学习/深度学习的入门概念', 'sparkles', 10, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:llm', 'zh', 'llm', '大语言模型', 'llm', 'LLM 的原理与关键术语', 'bot', 20, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:prompting', 'zh', 'prompting', '提示词与上下文', 'prompting', '怎么把任务“喂”给模型', 'message-square', 30, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:rag', 'zh', 'rag', '检索与知识(RAG)', 'rag', '让模型用外部知识回答', 'database', 40, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:ai-agent', 'zh', 'ai-agent', 'AI 智能体', 'ai-agent', '能规划、调工具、多步执行的 AI', 'workflow', 50, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:generative-ai', 'zh', 'generative-ai', '生成式与多模态', 'generative-ai', '文生图/视频/音频、多模态', 'image', 60, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:model-training', 'zh', 'model-training', '模型训练与微调', 'model-training', '模型怎么练出来/怎么调', 'cpu', 70, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:ai-protocol', 'zh', 'ai-protocol', 'AI 协议与互操作', 'ai-protocol', 'AI 应用之间/和外部如何连接', 'plug', 80, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:ai-coding', 'zh', 'ai-coding', 'AI 编程与开发工具', 'ai-coding', '用 AI 写代码/开发', 'code', 90, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:ai-safety', 'zh', 'ai-safety', '安全、评估与对齐', 'ai-safety', '让 AI 可靠、可信、可衡量', 'shield-check', 100, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:ai-ecosystem', 'zh', 'ai-ecosystem', 'AI 产品与生态', 'ai-ecosystem', '厂商、模型家族、产品', 'boxes', 110, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:zh:ai-trends', 'zh', 'ai-trends', 'AI 趋势与社会', 'ai-trends', '趋势、伦理、政策、黑话', 'trending-up', 120, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:ai-basics', 'en', 'ai-basics', 'AI Basics', 'ai-basics', 'Introductory concepts in AI, machine learning, and deep learning.', 'sparkles', 10, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:llm', 'en', 'llm', 'Large Language Models', 'llm', 'Core ideas and vocabulary around large language models.', 'bot', 20, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:prompting', 'en', 'prompting', 'Prompting & Context', 'prompting', 'How tasks, instructions, examples, and context are given to models.', 'message-square', 30, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:rag', 'en', 'rag', 'Retrieval & Knowledge', 'rag', 'Retrieval, knowledge bases, and external context for model answers.', 'database', 40, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:ai-agent', 'en', 'ai-agent', 'AI Agents', 'ai-agent', 'AI systems that plan, use tools, and carry out multi-step tasks.', 'workflow', 50, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:generative-ai', 'en', 'generative-ai', 'Generative & Multimodal', 'generative-ai', 'Image, video, audio, and multimodal generation.', 'image', 60, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:model-training', 'en', 'model-training', 'Training & Fine-tuning', 'model-training', 'How models are trained, adapted, compressed, and evaluated during training.', 'cpu', 70, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:ai-protocol', 'en', 'ai-protocol', 'Protocols & Interop', 'ai-protocol', 'Protocols and interfaces that connect AI apps, tools, and external systems.', 'plug', 80, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:ai-coding', 'en', 'ai-coding', 'AI Coding & Dev Tools', 'ai-coding', 'AI-assisted coding, developer tools, and software development workflows.', 'code', 90, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:ai-safety', 'en', 'ai-safety', 'Safety, Eval & Alignment', 'ai-safety', 'Reliability, evaluation, alignment, guardrails, and red-teaming.', 'shield-check', 100, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:ai-ecosystem', 'en', 'ai-ecosystem', 'Products & Ecosystem', 'ai-ecosystem', 'AI companies, model families, products, and ecosystem dynamics.', 'boxes', 110, unixepoch('now') * 1000, unixepoch('now') * 1000),
  ('ai-term-category:en:ai-trends', 'en', 'ai-trends', 'Trends & Society', 'ai-trends', 'AI trends, ethics, policy, copyright, and cultural vocabulary.', 'trending-up', 120, unixepoch('now') * 1000, unixepoch('now') * 1000)
ON CONFLICT(`locale`, `slug`) DO UPDATE SET
  `translation_key` = excluded.`translation_key`,
  `name` = excluded.`name`,
  `description` = excluded.`description`,
  `icon` = excluded.`icon`,
  `sort_order` = excluded.`sort_order`,
  `updated_at` = excluded.`updated_at`;
